version = 0.1

# Global settings
[default.global.parameters]
stack_name = "hono-hw"

# Build settings
[default.build.parameters]
cached = true
parallel = true
template = "infra/template.yaml"

# Deploy settings
[default.deploy.parameters]
capabilities          = "CAPABILITY_IAM"
confirm_changeset     = false
resolve_s3            = true
template_file         = "infra/template.yaml"
region                = "us-east-1"
parameter_overrides   = "DBUsername=postgres DBName=hono_hw"
